platform :ios, '8.0'
#use_frameworks!
#inhibit_all_warnings!

target 'VVModularity_Example' do
  pod 'VVModularity', :path => '../'

  target 'VVModularity_Tests' do
    inherit! :search_paths

  end
end
